---
- name: install apache & php & mysql
  hosts: hostservers
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Install apache2"
      package: name=apache2 state=present
    - name: "Install php"
      package: name=php state=present
    - name: "Install apache2-php5"
      package: name=libapache2-mod-php state=present
    - name: "Install php-cli"
      package: name=php-cli state=present
    - name: "Install php-dev"
      package: name=php-dev state=present
    - name: "Install php-pear"
      package: name=php-pear state=present
    - name: "Install php-gd"
      package: name=php-gd state=present
    - name: "Install php-mysql"
      package: name=php-mysql state=present
    - name: "Install mysqlserver"
      package: name=mysql-server state=present
    - name: Deploy static website
      copy: src=/home/himanshuchandan94/index.html dest=/var/www/html/index.html.
