---
- name: install apache & php & mysql
  hosts: hostservers
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Install apache2"
      package: name=apache2 state=present
    - name: "Install php"
      package: name=php state=present
    - name: "Install apache2-php5"
      package: name=libapache2-mod-php state=present
    - name: "Install php-cli"
      package: name=php-cli state=present
    - name: "Install php-dev"
      package: name=php-dev state=present
    - name: "Install php-pear"
      package: name=php-pear state=present
    - name: "Install php-gd"
      package: name=php-gd state=present
    - name: "Install php-mysql"
      package: name=php-mysql state=present
    - name: "Install mysqlserver"
      package: name=mysql-server state=present
    - name: Update Lists
      command: apt-get update
    - name: intall JDK
      apt:
        name: openjdk-11-jdk
        state: present
        # from here starts tomcat
    - name: Install add-apt-repostory
      become: yes
      apt: 
        name: software-properties-common
        state: latest 
    #- name: Add Oracle Java Repository
     # become: yes
     # apt_repository: repo='ppa:webupd8team/java'
    #- name: Accept Java 8 License
     # become: yes
     # debconf: name='oracle-Java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    #- name: Install oracle Java 8
     # become: yes
     # apt: name={{item}} state=latest 
     # with_items:
      #  - oracle.java8-installer
      #  - ca-certificates
      #  - oracle-java8-set-default
    - name: Create Folder
      file:
       path: /home/ubuntu/tomcat
       state: directory
       mode: 0755
       owner: ubuntu
       group: ubuntu
    - name: Download Tomcat
      get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/home/ubuntu/tomcat 
    - name: Extract archive
      unarchive: remote_src=/home/ubuntu/tomcat/apache-tomcat-8.0.27.tar.gz dest=/home/ubuntu/tomcat
    - name: start apache tomcat-8.0.27
      shell: /home/ubuntu/tomcat/apache-tomcat-8.0.27/bin/startup.sh
    - name: copy war file 
      shell: cp /var/lib/jenkins/workspace/student_data_101/bootjpa/target/bootjpa-0.0.1-SNAPSHOT.war /home/ubuntu/tomcat/apache-tomcat-8.0.27/webapps/
#here ends tomcat
   # - name: Deploy war file
    #  copy: src=/var/lib/jenkins/workspace/student_data_101/bootjpa/target/bootjpa-0.0.1-SNAPSHOT.war dest=/var/www/html/
